mysite/urls.py
from django.contrib import admin
from django.urls import path
from polls import views as polls_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', polls_views.index, name='index'),
    path('polls/<int:question_id>/result', polls_views.results, name='result'),
    path('polls/<int:question_id>', polls_views.detail, name='detail'),
    path('polls/<int:question_id>/vote', polls_views.vote, name='vote'),
]

polls/models.py
from django.db import models

# Create your models here.

class Questions(models.Model):
    pass 
    # 질문
    question_text = models.CharField(max_length=200)
    # 질문 생성 시각
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text    
    
    
class Choices(models.Model):
    pass
    # pk 
    # 초이스내용
    choice_text = models.CharField(max_length=200)
    # 질문 id 
    question = models.ForeignKey(Questions, on_delete=models.CASCADE)
    # 투표수
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text
    

polls/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.shortcuts import get_object_or_404

from .models import Questions, Choices


def index(request):
    latest_question_list = Questions.objects.all().order_by("-pub_date")[:5]
    context = {'latest_question_list':latest_question_list}
    return render(request, 'polls/index.html', context)

def results(request, question_id:int):
    return JsonResponse( {f"question_id {question_id}":"results"})

def detail(request, question_id:int):
    question = get_object_or_404(Questions, pk=question_id)    
    return render(request, 'polls/detail.html', {'question':question})

def vote(reqest, question_id:int):
    return JsonResponse( {f"question_id {question_id}":"vote"})

polls/templates/polls/detail.html
<h1>
    {{ question.question_text }}
</h1>

{% if error_message %}
    <p>
        <strong>{{ error_message }}</strong>
    </p>
{% endif %}
<form method="post" action="{% url 'vote' question.id %}">
    {% csrf_token %}
    {% for choice in question.choices_set.all%}
        <input type="radio" name="choice{{ forloop.couter }}"
                value="{{choice.id}}"/>
        <label for ="choice{{ forloop.counter}}">
            {{choice.choice_text}}
        </label>
        <br/>
    {% endfor %}
    <input type="submit" value="Vote"/>
</form>

polls/templates/polls/index.html
{% if latest_question_list %}

<ul>
    {% for question in latest_question_list %}
        <a href="/polls/{{ question.id }}">
            <h1>{{question}}</h1>
        </a>    
    {%endfor%}
</ul>


{% else %}
    <p>
        No polls are available
    </p>
{%endif%}